all: affichageTexte.o hephaistos.o types.o
	gcc affichageTexte.o hephaistos.o types.o -o projet_dessinatorV7
	
affichageTexte.o:
	gcc -c affichageTexte.c -o affichageTexte.o

hephaistos.o:
	gcc -c hephaistos.c -o hephaistos.o

types.o:
	gcc -c types.c -o types.o
